### ISSUE TITLE
Ethereum account refill

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/webGold-WRIO-App#138]
Кошельки пользователей пополнять до 0.01ETH с webRunes кошелька при первом зачислении средств и если сумма на кошельке становится меньше 0.002ETH. Деньги на пополнение счета за счет вычета % при донейте. При прямом переводе средств (не донейт) будет сниматься 1WRG для оплаты перевода.

**Comment by michbil** [comment]
0.01ETH может быть слишком маленькой суммой, проведу рассчеты и скажу минимально допустимую сумму для одной транзакции

**Comment by michbil** [comment]
Не все может тратиться за одну транзакцию, однако запас эфира на счету должен быть.

**Comment by michbil** [comment]
На данный момент минимальный остаток для успешной транзакции - 0.0188 ETH( не стоимость транзакции! )
Проверю возможно безболезненно уменьшить эту величину до 0.01ETH или менее.

**Comment by AlexeyAnshakov** [comment]
Не проблема, пусть будет 0.05ETH

**Comment by michbil** [comment]
@AlexeyAnshakov can be closed
