### ISSUE TITLE
Ethereum

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/webGold-WRIO-App#74]
We need to install Ethereum tools on the server. 
Command you need to run is: bash <(curl https://install-geth.ethereum.org -L)

Please refer to ethereum docs if needed https://www.ethereum.org/cli, we need go-based client GETH.

@michbil FYI.

**Comment by umairadeeb** [comment]
this is completed.

**Comment by AlexeyAnshakov** [comment]
@michbil please confirm

**Comment by michbil** [comment]
Working now
